In [4]:
import numpy as np

In [5]:
import csv

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
X = np.zeros((351, 34), dtype='float')

y = np.zeros((351,))

with open('ionosphere.data') as input_file:
    reader = csv.reader(input_file)
    for i, row in enumerate(reader):
        data = [float(datum) for datum in row[:-1]]
        X[i] = data
        y[i] = int(row[-1] == 'g')

In [11]:
y

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0

In [12]:
X

array([[ 1.     ,  0.     ,  0.99539, ..., -0.54487,  0.18641, -0.453  ],
       [ 1.     ,  0.     ,  1.     , ..., -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , ..., -0.2418 ,  0.56045, -0.38238],
       ..., 
       [ 1.     ,  0.     ,  0.94701, ...,  0.00442,  0.92697, -0.00577],
       [ 1.     ,  0.     ,  0.90608, ..., -0.03757,  0.87403, -0.16243],
       [ 1.     ,  0.     ,  0.8471 , ..., -0.06678,  0.85764, -0.06151]])

In [13]:
X_broken = np.array(X)

In [14]:
X_broken[:, ::2] /= 10

In [15]:
X_broken

array([[ 0.1     ,  0.      ,  0.099539, ..., -0.54487 ,  0.018641, -0.453   ],
       [ 0.1     ,  0.      ,  0.1     , ..., -0.06288 , -0.013738,
        -0.02447 ],
       [ 0.1     ,  0.      ,  0.1     , ..., -0.2418  ,  0.056045,
        -0.38238 ],
       ..., 
       [ 0.1     ,  0.      ,  0.094701, ...,  0.00442 ,  0.092697,
        -0.00577 ],
       [ 0.1     ,  0.      ,  0.090608, ..., -0.03757 ,  0.087403,
        -0.16243 ],
       [ 0.1     ,  0.      ,  0.08471 , ..., -0.06678 ,  0.085764,
        -0.06151 ]])

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
from sklearn.model_selection import cross_val_score

In [18]:
estimator = KNeighborsClassifier()

In [20]:
orginal_scores = cross_val_score(estimator, X, y, scoring='accuracy')

In [21]:
orginal_scores

array([ 0.82051282,  0.78632479,  0.86324786])

In [23]:
broken_scores = cross_val_score(estimator, X_broken, y, scoring='accuracy')

In [24]:
broken_scores

array([ 0.75213675,  0.64957265,  0.74358974])

In [25]:
X_transformed = MinMaxScaler().fit_transform(X)

In [26]:
X_transformed

array([[ 1.      ,  0.      ,  0.997695, ...,  0.227565,  0.593205,  0.2735  ],
       [ 1.      ,  0.      ,  1.      , ...,  0.46856 ,  0.43131 ,
         0.487765],
       [ 1.      ,  0.      ,  1.      , ...,  0.3791  ,  0.780225,
         0.30881 ],
       ..., 
       [ 1.      ,  0.      ,  0.973505, ...,  0.50221 ,  0.963485,
         0.497115],
       [ 1.      ,  0.      ,  0.95304 , ...,  0.481215,  0.937015,
         0.418785],
       [ 1.      ,  0.      ,  0.92355 , ...,  0.46661 ,  0.92882 ,
         0.469245]])