In [1]:
import numpy as np

In [2]:
arr = np.empty((8, 4))

In [4]:
for i in range(8):
    arr[i] = i

**以特定顺序选取子行**

In [5]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [6]:
arr[[3,1,2,4]]

array([[ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.]])

In [8]:
arr[[3, 1, 2, 4], [1, 2, 3, 0]]

array([ 3.,  1.,  2.,  4.])

In [10]:
arr[[3, 1, 2, 4]][:, [1, 2, 3, 0]]

array([[ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.]])

In [14]:
np.ix_?

花式索引总是将数组复制到新数组中