In [1]:
import numpy as np

In [2]:
xarr = np.random.rand(5) + 1

In [3]:
xarr

array([ 1.38113919,  1.68664464,  1.27795231,  1.83398149,  1.20723581])

In [4]:
yarr = np.random.rand(5) + 2

In [5]:
yarr

array([ 2.44443481,  2.43350034,  2.52487504,  2.24590965,  2.50591845])

In [6]:
cond = np.array([True, False, True, True, False])

In [7]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [8]:
result

[1.3811391894568068,
 2.4335003392882051,
 1.2779523103131594,
 1.8339814905493084,
 2.5059184510040469]

In [9]:
result1 = np.where(cond, xarr, yarr)

In [10]:
result1

array([ 1.38113919,  2.43350034,  1.27795231,  1.83398149,  2.50591845])