In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [9]:
arr = np.random.randn(10)

In [10]:
arr

array([-1.18382238, -2.74442918,  0.20834853, -0.10180308,  0.84471193,
        0.14749698,  1.35062142, -0.56975993, -0.43942724, -0.01342159])

In [11]:
np.abs(arr)

array([ 1.18382238,  2.74442918,  0.20834853,  0.10180308,  0.84471193,
        0.14749698,  1.35062142,  0.56975993,  0.43942724,  0.01342159])

In [12]:
np.sign(arr)

array([-1., -1.,  1., -1.,  1.,  1.,  1., -1., -1., -1.])

In [13]:
np.ceil(arr)

array([-1., -2.,  1., -0.,  1.,  1.,  2., -0., -0., -0.])

In [14]:
np.floor(arr)

array([-2., -3.,  0., -1.,  0.,  0.,  1., -1., -1., -1.])

In [15]:
np.rint(arr)

array([-1., -3.,  0., -0.,  1.,  0.,  1., -1., -0., -0.])

In [16]:
np.modf(arr)

(array([-0.18382238, -0.74442918,  0.20834853, -0.10180308,  0.84471193,
         0.14749698,  0.35062142, -0.56975993, -0.43942724, -0.01342159]),
 array([-1., -2.,  0., -0.,  0.,  0.,  1., -0., -0., -0.]))

In [17]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [18]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [22]:
arr1 = np.random.randn(2, 5)

In [23]:
arr1

array([[-0.26513129,  0.01061468,  1.3129734 , -1.46609115, -0.09135032],
       [ 0.15753962,  0.69932085,  1.27958808,  1.46082314,  0.59158272]])

In [24]:
arr2 = np.arange(10).reshape((2, 5))

In [25]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
np.add(arr1, arr2)

array([[-0.26513129,  1.01061468,  3.3129734 ,  1.53390885,  3.90864968],
       [ 5.15753962,  6.69932085,  8.27958808,  9.46082314,  9.59158272]])

In [27]:
np.maximum(arr1, arr2)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [28]:
np.copysign(arr1, arr2)

array([[ 0.26513129,  0.01061468,  1.3129734 ,  1.46609115,  0.09135032],
       [ 0.15753962,  0.69932085,  1.27958808,  1.46082314,  0.59158272]])