In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
adult = pd.read_csv('./Adult/adult.data', header=None,
                    names=['Age', 'Work-Class', 'fnlwgt', 'Education', 'Education-Num',
                          'Marital-Status', 'Occupation', 'Relationship', 'Race', 'Sex',
                          'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-Country',
                          'Earnings-Raw'])

In [4]:
adult[:10]

Age         Work-Class  fnlwgt   Education  Education-Num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           Marital-Status          Occupation    Relationship    Race  \
0           Never-married        Adm-clerical   Not-in-family   White   
1      Married-civ-spouse     Exec-managerial         Husband   White   
2                Divorced   Handlers-cleaners   Not-in-family   White   
3      Married-civ-spouse   Handlers-cleaners         Husband   Black   
4      Married-civ-spouse      Prof-specialty            Wife   Black   
5      Married-civ-spouse     Exec-managerial            Wife   White   
6   Married-spouse-absent       Other-service   Not-in-family   Black   
7      Married-civ-spouse     Exec-managerial         Husband   White   
8           Never-married      Prof-specialty   Not-in-family   White   
9      Married-civ-spouse     Exec-managerial         Husband   White   

       Sex  Capital-gain  Capital-loss  Hours-per-week  Native-Country  \
0     Male          2174             0              40   United-States   
1     Male             0             0              13   United-States   
2     Male             0             0              40   United-States   
3     Male             0             0              40   United-States   
4   Female             0             0              40            Cuba   
5   Female             0             0              40   United-States   
6   Female             0             0              16         Jamaica   
7     Male             0             0              45   United-States   
8   Female         14084             0              50   United-States   
9     Male          5178             0              40   United-States   

  Earnings-Raw  
0        <=50K  
1        <=50K  
2        <=50K  
3        <=50K  
4        <=50K  
5        <=50K  
6        <=50K  
7         >50K  
8         >50K  
9         >50K

In [5]:
adult.dropna(how='all', inplace=True)

In [6]:
adult.columns

Index(['Age', 'Work-Class', 'fnlwgt', 'Education', 'Education-Num',
       'Marital-Status', 'Occupation', 'Relationship', 'Race', 'Sex',
       'Capital-gain', 'Capital-loss', 'Hours-per-week', 'Native-Country',
       'Earnings-Raw'],
      dtype='object')

In [7]:
adult['Hours-per-week'].describe()

count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
Name: Hours-per-week, dtype: float64

In [8]:
adult['Work-Class'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay', ' Never-worked'], dtype=object)

In [10]:
adult['longHours'] = adult['Hours-per-week'] > 40

In [11]:
X = np.arange(30).reshape((10, 3))

In [12]:
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [13]:
X[:, 1] = 1

In [14]:
X

array([[ 0,  1,  2],
       [ 3,  1,  5],
       [ 6,  1,  8],
       [ 9,  1, 11],
       [12,  1, 14],
       [15,  1, 17],
       [18,  1, 20],
       [21,  1, 23],
       [24,  1, 26],
       [27,  1, 29]])

In [16]:
from sklearn.feature_selection import VarianceThreshold

In [17]:
vt = VarianceThreshold()

In [19]:
Xt = vt.fit_transform(X)

In [20]:
Xt

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11],
       [12, 14],
       [15, 17],
       [18, 20],
       [21, 23],
       [24, 26],
       [27, 29]])

In [22]:
print(vt.variances_)

[ 74.25   0.    74.25]


In [23]:
X = adult[['Age', 'Education-Num', 'Capital-gain', 'Capital-loss', 'Hours-per-week']].values

In [24]:
X[:10]

array([[   39,    13,  2174,     0,    40],
       [   50,    13,     0,     0,    13],
       [   38,     9,     0,     0,    40],
       [   53,     7,     0,     0,    40],
       [   28,    13,     0,     0,    40],
       [   37,    14,     0,     0,    40],
       [   49,     5,     0,     0,    16],
       [   52,     9,     0,     0,    45],
       [   31,    14, 14084,     0,    50],
       [   42,    13,  5178,     0,    40]])

In [25]:
y = (adult['Earnings-Raw'] == ' >50K').values

In [26]:
y

array([False, False, False, ..., False, False,  True], dtype=bool)

In [27]:
from sklearn.feature_selection import SelectKBest

In [28]:
from sklearn.feature_selection import chi2

In [29]:
transformer = SelectKBest(score_func=chi2, k=3)

In [30]:
Xt_chi2 = transformer.fit_transform(X, y)

In [31]:
Xt_chi2[:20]

array([[   39,  2174,     0],
       [   50,     0,     0],
       [   38,     0,     0],
       [   53,     0,     0],
       [   28,     0,     0],
       [   37,     0,     0],
       [   49,     0,     0],
       [   52,     0,     0],
       [   31, 14084,     0],
       [   42,  5178,     0],
       [   37,     0,     0],
       [   30,     0,     0],
       [   23,     0,     0],
       [   32,     0,     0],
       [   40,     0,     0],
       [   34,     0,     0],
       [   25,     0,     0],
       [   32,     0,     0],
       [   38,     0,     0],
       [   43,     0,     0]])

In [32]:
print(transformer.scores_)

[  8.60061182e+03   2.40142178e+03   8.21924671e+07   1.37214589e+06
   6.47640900e+03]


In [33]:
8e+2

800.0

In [34]:
from sklearn.base import TransformerMixin

In [35]:
from sklearn.utils import as_float_array

In [48]:
class MeanDiscreate(TransformerMixin):
    def fit(self, X):
        X = as_float_array(X)
        print(X)
        self.mean = X.mean(axis=0)
        return self
    def transform(self, X):
        X = as_float_array(X)
        assert X.shape[1] == self.mean.shape[0]
        return X > self.mean

In [49]:
mean_discrete = MeanDiscreate()

In [50]:
X = pd.DataFrame(np.arange(12).reshape((3, 4)), columns=['a', 'b', 'c', 'd'])

In [51]:
re = mean_discrete.fit(X)

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]


In [52]:
re.mean

array([ 4.,  5.,  6.,  7.])

In [53]:
X

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [54]:
X_mean = mean_discrete.fit_transform(X)

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]


In [55]:
X_mean

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]], dtype=bool)

In [56]:
from numpy.testing import assert_array_equal