In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [6]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [7]:
import numpy.linalg as lg

In [8]:
X = np.random.randn(5, 5)

In [9]:
X

array([[ 0.3598073 , -1.56549139,  0.14969773,  0.73893513, -0.20078384],
       [-0.75469088,  0.37564209,  0.61808181,  0.82919012, -0.19304834],
       [ 1.27862907,  0.05113217,  0.19854794,  1.35530979, -0.47478688],
       [ 0.94951898,  0.25758402, -0.90991471,  0.80668488,  0.67605914],
       [ 0.62754448, -0.06289589,  2.2011317 ,  0.05951003, -2.39766307]])

In [10]:
lg.inv(X)

array([[  5.02595775,   6.33070553, -24.4890881 ,  29.13771704,
         12.13458834],
       [ -0.84392561,  -0.20159189,   1.43035468,  -1.37968928,  -0.5853623 ],
       [ 13.46230325,  18.16035965, -65.07924236,  76.00030904,  31.7269906 ],
       [ -1.90038604,  -2.22196163,  10.22207086, -11.54517022,
         -4.94148252],
       [ 13.64924969,  18.2788789 , -65.93821503,  77.14663021,
         31.77803784]])

In [11]:
X = np.floor(X)

In [12]:
X

array([[ 0., -2.,  0.,  0., -1.],
       [-1.,  0.,  0.,  0., -1.],
       [ 1.,  0.,  0.,  1., -1.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0., -1.,  2.,  0., -3.]])

In [15]:
lg.svd(X)

(array([[-0.37559951,  0.89053852,  0.07786571,  0.14373381, -0.19784761],
        [-0.191181  , -0.01438144, -0.43901687, -0.76504418, -0.43036566],
        [-0.20415867, -0.17822367,  0.87409308, -0.28927955, -0.28077426],
        [ 0.10487067,  0.28936126,  0.14813069, -0.54670392,  0.76448959],
        [-0.87732332, -0.30206077, -0.12336815,  0.10714554,  0.33520622]]),
 array([ 4.21088228,  1.75720693,  1.63268684,  1.17981743,  0.35079734]),
 array([[-0.00308194,  0.38674136, -0.44159803, -0.04848359,  0.8081226 ],
        [-0.09324014, -0.84168588, -0.50846761, -0.10142441,  0.11851132],
        [ 0.8042632 , -0.01982209, -0.24185103,  0.53537093, -0.08748614],
        [ 0.40325275, -0.33446968,  0.64501081, -0.2451901 ,  0.49935971],
        [ 0.42643253,  0.17243291, -0.26818092, -0.80038879, -0.2754614 ]]))

In [16]:
np.diag(X)

array([ 0.,  0.,  0.,  0., -3.])